<?php

namespace app\models;

use PhpOffice\PhpSpreadsheet\Style\NumberFormat\Wizard\Date;
use Yii;

/**
 * This is the model class for table "file_name".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $date
 *
 * @property FileData[] $fileDatas
 */
class FileName extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'file_name';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date'], 'safe'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'date' => 'Date',
        ];
    }

    /**
     * Gets query for [[FileDatas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFileDatas()
    {
        return $this->hasMany(FileData::class, ['file_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->date = Yii::$app->formatter->asDate(new \DateTime(), 'php:Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
